<?xml version="1.0" encoding="utf-8"?><Database Name="karo" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DUY-LAPTOP\SQLEXPRESS;Initial Catalog=karo;Persist Security Info=True;User ID=sa" SettingsObjectName="server.Properties.Settings" SettingsPropertyName="karoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="win" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lose" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="draw" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>